version: '3'
services:
  placeholder.generator:
    image: 'placeholder.generator:dev'
    build:
      context: ../app.placeholder.generator/
      dockerfile: docker/development.dockerfile
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on: []
    volumes:
      - '../app.placeholder.generator/:/app/'
    environment:
      - NODE_ENV=development
      - PORT=3000
