version: '3'
services:
  placeholder.generator:
    image: 'placeholder.generator:dev'
    build:
      context: ../app.placeholder.generator/
      dockerfile: docker/development.dockerfile
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on: []
    volumes:
      - '../app.placeholder.generator/:/app/'
    environment:
      - NODE_ENV=development
      - PORT=3000
#  cms:
#    image: 'cms:dev'
#    build:
#      context: ../app.cms/
#      dockerfile: docker/development.dockerfile
#    expose:
#      - '1337'
#    ports:
#      - '1337:1337'
#    depends_on:
#      - db
#    volumes:
#      - '../app.cms/:/app/'
##    environment:
##      - NODE_ENV=development
##      - PORT=3000
  db:
    image: postgres
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: legacy
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
  db.gui:
    image: adminer
    expose:
      - '8080'
    ports:
      - '8080:8080'
